/**
 * This class is generated by jOOQ
 */
package com.github.lburgazzoli.sandbox.jooq.db.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TestRecord extends org.jooq.impl.TableRecordImpl<com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord> implements org.jooq.Record2<java.lang.Integer, java.lang.String>, com.github.lburgazzoli.sandbox.jooq.db.tables.interfaces.ITest {

	private static final long serialVersionUID = -2133450423;

	/**
	 * Setter for <code>PUBLIC.TEST.ID</code>.
	 */
	public TestRecord setId(java.lang.Integer value) {
		setValue(0, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.TEST.ID</code>.
	 */
	@Override
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>PUBLIC.TEST.DATA</code>.
	 */
	public TestRecord setData(java.lang.String value) {
		setValue(1, value);
		return this;
	}

	/**
	 * Getter for <code>PUBLIC.TEST.DATA</code>.
	 */
	@Override
	public java.lang.String getData() {
		return (java.lang.String) getValue(1);
	}

	// -------------------------------------------------------------------------
	// Record2 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row2) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row2<java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row2) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return com.github.lburgazzoli.sandbox.jooq.db.tables.Test.TEST.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.github.lburgazzoli.sandbox.jooq.db.tables.Test.TEST.DATA;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getData();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestRecord value2(java.lang.String value) {
		setData(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TestRecord values(java.lang.Integer value1, java.lang.String value2) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TestRecord
	 */
	public TestRecord() {
		super(com.github.lburgazzoli.sandbox.jooq.db.tables.Test.TEST);
	}

	/**
	 * Create a detached, initialised TestRecord
	 */
	public TestRecord(java.lang.Integer id, java.lang.String data) {
		super(com.github.lburgazzoli.sandbox.jooq.db.tables.Test.TEST);

		setValue(0, id);
		setValue(1, data);
	}
}
