/**
 * This class is generated by jOOQ
 */
package com.github.lburgazzoli.sandbox.jooq.db.tables.interfaces;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public interface ITest extends java.io.Serializable {

	/**
	 * Getter for <code>PUBLIC.TEST.ID</code>.
	 */
	public java.lang.Integer getId();

	/**
	 * Getter for <code>PUBLIC.TEST.DATA</code>.
	 */
	public java.lang.String getData();
}
