/**
 * This class is generated by jOOQ
 */
package com.github.lburgazzoli.sandbox.jooq.db.tables.pojos;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test implements com.github.lburgazzoli.sandbox.jooq.db.tables.interfaces.ITest {

	private static final long serialVersionUID = -1837765882;

	private final java.lang.Integer id;
	private final java.lang.String  data;

	public Test(
		java.lang.Integer id,
		java.lang.String  data
	) {
		this.id = id;
		this.data = data;
	}

	@Override
	public java.lang.Integer getId() {
		return this.id;
	}

	@Override
	public java.lang.String getData() {
		return this.data;
	}
}
