/**
 * This class is generated by jOOQ
 */
package com.github.lburgazzoli.sandbox.jooq.db;

/**
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.4"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.TEST
	 */
	public static final com.github.lburgazzoli.sandbox.jooq.db.tables.Test TEST = com.github.lburgazzoli.sandbox.jooq.db.tables.Test.TEST;
}
