/**
 * This class is generated by jOOQ
 */
package com.github.lburgazzoli.sandbox.jooq.db;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in PUBLIC
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table PUBLIC.TEST
	 */
	public static final com.github.lburgazzoli.sandbox.jooq.db.tables.Test TEST = com.github.lburgazzoli.sandbox.jooq.db.tables.Test.TEST;
}
