/**
 * This class is generated by jOOQ
 */
package com.github.lburgazzoli.sandbox.jooq.db.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Test extends org.jooq.impl.TableImpl<com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord> {

	private static final long serialVersionUID = 63251305;

	/**
	 * The singleton instance of <code>PUBLIC.TEST</code>
	 */
	public static final com.github.lburgazzoli.sandbox.jooq.db.tables.Test TEST = new com.github.lburgazzoli.sandbox.jooq.db.tables.Test();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord> getRecordType() {
		return com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord.class;
	}

	/**
	 * The column <code>PUBLIC.TEST.ID</code>.
	 */
	public final org.jooq.TableField<com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord, java.lang.Integer> ID = createField("ID", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>PUBLIC.TEST.DATA</code>.
	 */
	public final org.jooq.TableField<com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord, java.lang.String> DATA = createField("DATA", org.jooq.impl.SQLDataType.VARCHAR.length(2147483647), this, "");

	/**
	 * Create a <code>PUBLIC.TEST</code> table reference
	 */
	public Test() {
		this("TEST", null);
	}

	/**
	 * Create an aliased <code>PUBLIC.TEST</code> table reference
	 */
	public Test(java.lang.String alias) {
		this(alias, com.github.lburgazzoli.sandbox.jooq.db.tables.Test.TEST);
	}

	private Test(java.lang.String alias, org.jooq.Table<com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord> aliased) {
		this(alias, aliased, null);
	}

	private Test(java.lang.String alias, org.jooq.Table<com.github.lburgazzoli.sandbox.jooq.db.tables.records.TestRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.github.lburgazzoli.sandbox.jooq.db.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.github.lburgazzoli.sandbox.jooq.db.tables.Test as(java.lang.String alias) {
		return new com.github.lburgazzoli.sandbox.jooq.db.tables.Test(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.github.lburgazzoli.sandbox.jooq.db.tables.Test rename(java.lang.String name) {
		return new com.github.lburgazzoli.sandbox.jooq.db.tables.Test(name, null);
	}
}
